/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as NotreHistoireRouteImport } from './routes/notre-histoire'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminProduitsRouteImport } from './routes/admin.produits'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as AdminProduitsIdRouteImport } from './routes/admin.produits.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const NotreHistoireRoute = NotreHistoireRouteImport.update({
  id: '/notre-histoire',
  path: '/notre-histoire',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduitsRoute = AdminProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AdminRoute,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProduitsIdRoute = AdminProduitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProduitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/boutique': typeof BoutiqueRoute
  '/notre-histoire': typeof NotreHistoireRoute
  '/panier': typeof PanierRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/produits': typeof AdminProduitsRouteWithChildren
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/produits/$id': typeof AdminProduitsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/boutique': typeof BoutiqueRoute
  '/notre-histoire': typeof NotreHistoireRoute
  '/panier': typeof PanierRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/produits': typeof AdminProduitsRouteWithChildren
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/produits/$id': typeof AdminProduitsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/boutique': typeof BoutiqueRoute
  '/notre-histoire': typeof NotreHistoireRoute
  '/panier': typeof PanierRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/produits': typeof AdminProduitsRouteWithChildren
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/produits/$id': typeof AdminProduitsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/boutique'
    | '/notre-histoire'
    | '/panier'
    | '/admin/clients'
    | '/admin/collections'
    | '/admin/produits'
    | '/produit/$slug'
    | '/admin/produits/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/boutique'
    | '/notre-histoire'
    | '/panier'
    | '/admin/clients'
    | '/admin/collections'
    | '/admin/produits'
    | '/produit/$slug'
    | '/admin/produits/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/boutique'
    | '/notre-histoire'
    | '/panier'
    | '/admin/clients'
    | '/admin/collections'
    | '/admin/produits'
    | '/produit/$slug'
    | '/admin/produits/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BoutiqueRoute: typeof BoutiqueRoute
  NotreHistoireRoute: typeof NotreHistoireRoute
  PanierRoute: typeof PanierRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notre-histoire': {
      id: '/notre-histoire'
      path: '/notre-histoire'
      fullPath: '/notre-histoire'
      preLoaderRoute: typeof NotreHistoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produits': {
      id: '/admin/produits'
      path: '/produits'
      fullPath: '/admin/produits'
      preLoaderRoute: typeof AdminProduitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produits/$id': {
      id: '/admin/produits/$id'
      path: '/$id'
      fullPath: '/admin/produits/$id'
      preLoaderRoute: typeof AdminProduitsIdRouteImport
      parentRoute: typeof AdminProduitsRoute
    }
  }
}

interface AdminProduitsRouteChildren {
  AdminProduitsIdRoute: typeof AdminProduitsIdRoute
}

const AdminProduitsRouteChildren: AdminProduitsRouteChildren = {
  AdminProduitsIdRoute: AdminProduitsIdRoute,
}

const AdminProduitsRouteWithChildren = AdminProduitsRoute._addFileChildren(
  AdminProduitsRouteChildren,
)

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminProduitsRoute: typeof AdminProduitsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminProduitsRoute: AdminProduitsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BoutiqueRoute: BoutiqueRoute,
  NotreHistoireRoute: NotreHistoireRoute,
  PanierRoute: PanierRoute,
  ProduitSlugRoute: ProduitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
